#!/usr/bin/env bash

if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
  #scp -i PATH_to_ssh_key PATH_TO_FILE username@ip
  FILE_PATH="$1"
  SERVER_IP="$2"
  USERNAME="$3"
  SSH_KEY="$4"
  
  scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
fi


# Assign parameters to variables


# Transfer file using scp

