#!/usr/bin/env bash

if [ "$# -lt 3"]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
  #scp -i PATH_to_ssh_key PATH_TO_FILE username@ip
  scp -i "$4" "$1" "$3"@"$2":~/
fi 
