#!/usr/bin/env bash
#script to install nginx
start nginx
sudo ufw allow 'Nginx HTTPS' #allows nginx on the firewall
#change owner to user with the user group
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/

#backup the defualt nginx page
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.bak

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
