#!/usr/bin/env bash
#script to configure nginx with a custom webpage
##!/usr/bin/env bash

# Start nginx
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTPS'

# Change owner to current user
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/

# Backup the default nginx page
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.bak
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create a new index page
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Create a custom 404 error page
echo -e "Ceci n'est pas une page" > /var/www/html/404_notfound.html

# Configure the custom 404 error page
sudo sed -i '44i\       error_page 404 /404_notfound.html;\
                        location = /404_notfound.html {\
                        root /var/www/html;\
                        internal;}' /etc/nginx/sites-available/default
# Restart nginx to apply changes
sudo service nginx restart
