#!/usr/bin/env bash
#script to install and configure the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

#backup haproxy cfg file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

#add frontend configuration to haproxy
echo -e "\nfrontend web_frontend\n\
    bind *:80\n\
    mode http\n\
    default_backend web_backend" | sudo tee -a /etc/haproxy/haproxy.cfg

#add backend configuration to haproxy
echo -e "\nbackend web_backend\n\
    balance roundrobin\n\
    server 463484-web-01 54.86.227.214:80 check\n\
    server 463484-web-02 3.85.1.230:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
#restart haproxy service
sudo service haproxy restart
