#!/usr/bin/env bash
# script to create a backup db

password = $1
sudo mysqldump -u root -p $password --all-databases > backup.sql 
timestamp=$(date +'%d%m%Y%S')
backup_tar = "$timestamp.tar.gz"
tar -czf "$backup_tar" "backup.sql"
