#!/usr/bin/env bash
#script to satrt a =nginx and make sure its working on port80
sudo apt-get -y update
sudo apt -y install ufw
sudo ufw allow 80/tcp
sudo apt -y install nginx

#symlink available-defualt to enabled
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx to effect changes.
sudo service nginx restart

