#!/usr/bin/env bash
#script to satrt a =nginx and make sure its working on port80
sudo apt-get -y update
sudo apt -y install ufw
sudo ufw allow 80/tcp
sudo apt -y install nginx
sudo service nginx restart
