#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0
minute=1
while [ $hour -lt 13 ]
do
    echo "Hour :$hour"
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		minute=$((minute + 1))
	done
	
	((hour++))
	((minute = 1))

done
