#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

file="school"
if [ -e $file ];then
	echo "school file exists"
	if [ -s $file ];then
		echo "school file is not empty"
	elif  ! [ -s $file ];then
		echo "school file is empty"
	fi
	if [ -f $file ];then
		echo "school is a regular file"
	elif ! [ -f $file ];then
		:
	fi
else
	echo "school file does not exist"
fi
