#!/usr/bin/bash
# Update package lists
sudo apt update

# Install ufw if not already installed
sudo apt install ufw

#enable firwall 
sudo ufw enable

# Set default policy to deny incoming traffic
sudo ufw default deny incoming

# Allow SSH (port 22), HTTPS (port 443), and HTTP (port 80)
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# Enable ufw
sudo ufw reload
