#!/usr/bin/env bash
#! code thagt changes the local host and adds facebook to 8.8.8.8
cp /etc/hosts ~/hosts.new

sed 's/127.0.0.1/127.0.0.2' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
